### ISSUE TITLE
bug: When piping into jlv, colors are lost

### ISSUE THREAD

**Issue by kiesel** [hedhyw/json-log-viewer#105]
When I run

    $ some-command | jlv

I don't have colored log levels - different from when opening a file w/ `jlv somelog.json`.

Probably the interactive terminal detection goes wrong due to stdin being used?

**Comment by hedhyw** [comment]
could it be that `some-command` also uses colors?

Plain experiment:
```
echo '{"msg":"test","level":"debug"}' | jlv
```

**Comment by kiesel** [comment]
The experiment yields jlv with colored debug; however, the original program does in fact only emit json logs, nothing else. It is a nodejs process.

This sample, though, also shows colors:

    $ node -e 'console.log(JSON.stringify({msg: "test", level: "debug"})); console.log(JSON.stringify({msg:"error", level: "error"}));' | jlv

I will investigate the original script.

**Comment by hedhyw** [comment]
Fixed in #113

**Comment by kiesel** [comment]
Awesome, I can confirm it works as expected now. Thank you!
