### ISSUE TITLE
feat: Formatting date

### ISSUE THREAD

**Issue by kiesel** [hedhyw/json-log-viewer#107]
The date formatting eats up quite a lot of size of a row; for some logs, it would be nice to only display the time part of a date, so an config option to format date strings would be nice.

**Comment by hedhyw** [comment]
There's a new field in the config:
https://github.com/hedhyw/json-log-viewer/blob/984a4b39bcbce2300fb1519ba71c8ef35a943001/example.jlv.jsonc#L35
