### ISSUE TITLE
feat: support sorting by field

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/json-log-viewer#17]
Add an ability to sort by field:
- Descending
- Ascending

**Comment by arsalankone** [comment]
Hi I want to work on it. Can you please explain what do you mean by _Show the list of fields to sort by_ ?

**Comment by hedhyw** [comment]
> Hi I want to work on it. 

Hi! Thank you.

> Can you please explain what do you mean by _Show the list of fields to sort by_ ?

The idea was to show a list of fields from which we can select a field to sort by, but of course, it's not a requirement.
Feel free to describe how you see it at its best.

**Comment by SpoonBuoy** [comment]
He @hedhyw assign it to me on this account, @arsalankone is my work account and I had mistakenly commented from that account.

I might need some help also in understanding the flow of code properly. Also like in sorting by fields, what criterion should be used for sorting mechanism. Sorting by value in case of timestamps and lexicographical sorting in message makes sense, but for level fields, what should be an appropriate parameter?

**Comment by hedhyw** [comment]
> I might need some help also in understanding the flow of code properly.
- Clicking hotkeys ("O"/"F6") on `StateLoaded`, `StateFiltered` should open a dialogue to select a field to sort by:
    - We need to create a new state (=bubble tea model) for the window that configures the sort order.
      https://github.com/hedhyw/json-log-viewer/blob/c65754ff6ef294d9d1d9653c105c8cda3e86dc80/internal/app/state.go#L9
      > There are many examples: `StateError`, `StateInitial`, `StateFiltering`, etc.
    - Possible widgets to use: https://github.com/charmbracelet/bubbles#list or https://github.com/charmbracelet/bubbles#table.
    - It would be nice to be able to reset the sorting to defaults (unsorted, as lines appear in the file).
    - Submitting: [Enter] -> configure and sort in descending order, [A] -> configure and sort in ascending order.
    - Make sure hotkeys do not influence `StateFiltering`.
- Possible sorting fields can be taken from the config:
    https://github.com/hedhyw/json-log-viewer/blob/c65754ff6ef294d9d1d9653c105c8cda3e86dc80/internal/pkg/config/config.go#L21
- The current sorting order can be stored in the persistent application state (available in all models, note: each local state [clones](https://github.com/hedhyw/json-log-viewer/blob/c65754ff6ef294d9d1d9653c105c8cda3e86dc80/internal/app/statefiltering.go#L57C26-L57C41) it). `StateLoaded` and `StateFiltered` will sort considering sorting configuration from the persistent state:
    https://github.com/hedhyw/json-log-viewer/blob/c65754ff6ef294d9d1d9653c105c8cda3e86dc80/internal/app/app.go#L11

> Sorting by value in case of timestamps and lexicographical sorting in message makes sense, but for level fields, what should be an appropriate parameter?

- Numbers/Timestamps -> by value.
- Any other value -> lexicographical.

**Comment by SpoonBuoy** [comment]
Can you take a look at it and see if I am following the right approach?
https://github.com/SpoonBuoy/json-log-viewer/tree/spoon

**Comment by hedhyw** [comment]
@SpoonBuoy do you still need this feature?

**Comment by hedhyw** [comment]
Closed as inactive
