### ISSUE TITLE
feat: support "ts" as a time field

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/json-log-viewer#26]

**Comment by Mihai22125** [comment]
Hi @hedhyw, I'd like to work on this issue. Can you assign it to me, please?

**Comment by hedhyw** [comment]
https://github.com/hedhyw/json-log-viewer/blob/aa8e0d34bd62e3423ee67b3b4163458793af2c47/internal/pkg/source/helper.go#L11

**Comment by hedhyw** [comment]
Resolved in https://github.com/hedhyw/json-log-viewer/pull/27
