### ISSUE TITLE
feat: improve toolbar with hotkeys

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/json-log-viewer#43]
Current toolbar:
![image](https://github.com/hedhyw/json-log-viewer/assets/19246753/c57e1f75-863d-4a4d-9a84-415bc556324f)

Use [key bindings](https://github.com/charmbracelet/bubbles#key). Different states should have different key bindings.
And show [help](https://github.com/charmbracelet/bubbles#help) in the toolbar.

**Comment by Vedu1996** [comment]
I'd like to pick this up :)

**Comment by hedhyw** [comment]
cool, thank you!
