### ISSUE TITLE
Support watch

### ISSUE THREAD

**Issue by wdanilo** [hedhyw/json-log-viewer#52]
Would it be possible to add watch support that:
1. If scrolled bottom, will auto-scroll when new logs appear
2. If scrolled a little bit up, will not auto-scroll
3. Will have a shortcut to scroll to bottom

:)

**Comment by hedhyw** [comment]
https://github.com/hedhyw/json-log-viewer/blob/327c116fbce61cd86d6e2322bed4965bdbf87c89/internal/app/stateloaded.go#L73C12-L73C44

**Comment by hedhyw** [comment]
implemented in https://github.com/hedhyw/json-log-viewer/pull/85
