### ISSUE TITLE
Reading from stdin

### ISSUE THREAD

**Issue by kolypto** [hedhyw/json-log-viewer#55]
Currently it's not possible to read from stdin:

```console
$ docker logs tasks 2>&1 | ./jlv -
Something went wrong: os: open -: no such file or directory.
```

A workaround is to use [bash process substitution](https://tldp.org/LDP/abs/html/process-sub.html):

```console
$ ./jlv <(docker logs tasks 2>&1)
```

**Comment by hedhyw** [comment]
another way around is to use `tee`.

```sh
docker logs tasks | tee tasks.logs
jlv tasks.logs
```

btw, it's planned to be implemented! thanks for the issue!

**Comment by hedhyw** [comment]
added in v0.5.1
