### ISSUE TITLE
v0.5.1 weird loading screen delay

### ISSUE THREAD

**Issue by FKPSC** [hedhyw/json-log-viewer#79]
It appears to take much longer to load the log data but I found out that just a "rendering" issue.
If I just open a log file and do nothing it can take a very long time (+30s) to open even files with 8 lines.
If after opening a log file I hit `Esc` every second or so, I get the log rows within ~2-3 seconds.
This is especially significant in bigger files.

**Comment by hedhyw** [comment]
Thank you for the issue!
Difficult to reproduce (but possible from Nth attempt), please try `v0.5.2`. If it doesn't work, can you please include OS information?

**Comment by hedhyw** [comment]
fixed in https://github.com/hedhyw/json-log-viewer/pull/85
